- hosts: serwery1
  remote_user: root
  vars:
   ansible_ssh_private_key_file: "/home/proseti/.ssh/id_rsa"
  tasks:
  - name: Move foo to bar
    copy: remote_src=True src=/exercise1/file_001 dest=/exercise1/nowy



